# Troy Clendenen
# printroute.py

def PrintRoute(routelist):

	'''
		PrintRoute()
		Author: Troy Clendenen

		This program will take in a list of tuples generated by
		getDirections() and iterate through that list to generate
		a readable version of the route taken from the inputted GPX
		file.

		inputs: routelist, a list of tuples in the form of (roadname,
		turn direction, distance in miles)
		outputs: a list of strings in order of the route that was
		taken.
	'''

	currentRoad = None # this will store our current road we are travelling on
	route = [] # the list we will return

	for entry in routelist:

		if (entry[2] != 0): # if the distance travelled != 0
			if (currentRoad != None): # for the edge case on the first call
				if (currentRoad[0] == entry[0]) and (entry[1] != "Uturn"): # if the road names are equal and there was no uturn
					currentRoad[2] += entry[2] # add the distance continued on this road

				else: # we add this section of the route in a readable format to our list
					route.append(currentRoad[1] + " on " + currentRoad[0] + " for " + str(round(currentRoad[2],2)) + " miles.")
					currentRoad = entry

			else:
				currentRoad = entry

	route.append(currentRoad[1] + " on " + currentRoad[0] + " for " + str(round(currentRoad[2],2)) + " miles.")
	return route

'''
help(PrintRoute)
'''